SELECT qurNewStorePipelineCurrentYearFranchiseInterestStepThree.Q1, qurNewStorePipelineCurrentYearFranchiseInterestStepThree.Q2, qurNewStorePipelineCurrentYearFranchiseInterestStepThree.Q3, qurNewStorePipelineCurrentYearFranchiseInterestStepThree.Q4, [Q1]+[Q2]+[Q3]+[Q4] AS Total
FROM qurNewStorePipelineCurrentYearFranchiseInterestStepThree;

