SELECT qurNewStorePipelineCurrentYearCommittedCorporateStepThree.Q1, qurNewStorePipelineCurrentYearCommittedCorporateStepThree.Q2, qurNewStorePipelineCurrentYearCommittedCorporateStepThree.Q3, qurNewStorePipelineCurrentYearCommittedCorporateStepThree.Q4, [Q1]+[Q2]+[Q3]+[Q4] AS Total
FROM qurNewStorePipelineCurrentYearCommittedCorporateStepThree;

